name: Build and test

on:
  push:
    branches: [ master, develop, feature/**, hotfix/**, release/**, bugfix/** ]
  pull_request:
    branches: [ develop, master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore src/CSharp/Egress.sln
    - name: Build
      run: dotnet build --configuration Release --no-restore src/CSharp/Egress.sln
    - name: Test
      run: dotnet test --no-restore --verbosity normal src/CSharp/Egress.sln
